name: Deploy Flask App to Azure via OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: fc4dd0f1-5a6a-4d23-8f8b-2a08438f5aa3
  AZURE_TENANT_ID: ce4136a6-8dad-47c5-9cdc-ddc03da55699
  AZURE_SUBSCRIPTION_ID: c63e6fcf-6839-452f-bc65-ef771e04d78e
  AZURE_WEBAPP_NAME: flask-monitor-poornesh  # Replace with your actual App Service name
  AZURE_RESOURCE_GROUP: flask-monitoring-rg  # Replace with your actual Resource Group name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: .
