name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: fc4dd0f1-5a6a-4d23-8f8b-2a08438f5aa3
        tenant-id: ce4136a6-8dad-47c5-9cdc-ddc03da55699
        subscription-id: 3752d2f8-6ef2-4533-8ac8-3f4a0e631329

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: flask-devops-app
        package: .
        resource-group-name: devdevops-flask-rg

