name: Build and Deploy Flask App to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # Required for OIDC
  contents: read        # Required to checkout code

jobs:
  build-and-deploy:
    name: Build and Deploy to Azure Web App
    runs-on: ubuntu-latest
    environment: Production  # Case-sensitive! Must match Entra ID

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: fc4dd0f1-5a6a-4d23-8f8b-2a08438f5aa3
          tenant-id: 9e8b270d-a269-4e85-8929-daba5017ec79
          subscription-id: c63e6fcf-6839-452f-bc65-ef771e04d78e

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: flask-devops-app
          slot-name: Production
          package: .
