name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # This must match EXACTLY (case-sensitive) with your GitHub environment name

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: fc4dd0f1-5a6a-4d23-8f8b-2a08438f5aa3
          tenant-id: ce4136a6-8dad-47c5-9cdc-ddc03da55699
          subscription-id: c63e6fcf-6839-452f-bc65-ef771e04d78e  # Update if changed

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: flask-devops-app  # Replace with your actual web app name
          package: .
