name: Build and Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: fc4dd0f1-5a6a-4d23-8f8b-2a08438f5aa3
  AZURE_SUBSCRIPTION_ID: 3752d2f8-6ef2-4533-8ac8-3f4a0e631329
  AZURE_TENANT_ID: ce4136a6-8dad-47c5-9cdc-ddc03da55699
  RESOURCE_GROUP: devops-flask-rg
  WEBAPP_NAME: flask-webapp-poornesh472  # ✅ updated app name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧪 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 🔧 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🛠️ Build (optional)
        run: echo "Build step (if needed)"

      - name: 🔐 Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: 🚀 Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: production
          package: .
